const Theme = {
  'light': {
    name: 'light',
    backgroundColor: '#F3F2F7',
    bookCardBGColor: '#FEFEFE',
    cardBGColor: '#FEFEFE',
    navBarBGColor: '#8B82FF',
    bookTitleColor: '#7670FF',
    bookAuthorsColor: '#111111',
    starColor: '#8B82FF',
    iconColor: '#8B82FF',
    sectionHeaderColor: '#212529',
    textColor: '#333333',
    usernameColor: '#7670FF',
    textFieldActiveColor: '#7670FF',
    chipColor: '#7670FF',
    progressPathColor: '#7670FF',
    progressTrailColor: '#CCCCCC',
    progressTextColor: '#7670FF',
    readerBackgroundColor: '#FEFEFE',
    readerTextColor: '#111111',
    primaryButtonColor: '#7670FF',
    notFoundDisplayColor: '#7670FF',
    notFoundColorFilter: 'invert(66%) sepia(52%) saturate(7490%) hue-rotate(220deg) brightness(99%) contrast(105%)',
  },
  'dark': {
    name: 'dark',
    backgroundColor: '#242526',
    bookCardBGColor: '#3A3B3C',
    cardBGColor: '#3A3B3C',
    navBarBGColor: '#18191A',
    bookTitleColor: '#FEFEFE',
    bookAuthorsColor: '#EEEEEE',
    starColor: '#FEFEFE',
    iconColor: '#FEFEFE',
    sectionHeaderColor: '#FEFEFE',
    textColor: '#EEEEEE',
    usernameColor: '#FEFEFE',
    textFieldActiveColor: '#BBBBBB',
    chipColor: '#242526',
    progressPathColor: '#FEFEFE',
    progressTrailColor: '#888888',
    progressTextColor: '#FEFEFE',
    readerBackgroundColor: '#333333',
    readerTextColor: '#FEFEFE',
    primaryButtonColor: '#3A3B3C',
    notFoundDisplayColor: '#FEFEFE',
    notFoundColorFilter: 'invert(99%) sepia(100%) saturate(1%) hue-rotate(69deg) brightness(104%) contrast(99%)',
  }
};

export default Theme;
