const Theme = {
  'light': {
    name: 'light',
    backgroundColor: '#F3F2F7',
    bookCardBGColor: '#FEFEFE',
    cardBGColor: '#FEFEFE',
    navBarBGColor: '#8B82FF',
    bookTitleColor: '#7670FF',
    bookAuthorsColor: '#111111',
    starColor: '#8B82FF',
    sectionHeaderColor: '#212529',
    textColor: '#333333',
    usernameColor: '#7670FF',
    textFieldActiveColor: '#7670FF',
    chipColor: '#7670FF',
    progressPathColor: '#7670FF',
    progressTrailColor: '#CCCCCC',
    progressTextColor: '#7670FF',
    readerBackgroundColor: '#FEFEFE',
    readerTextColor: '#111111',
  },
  'dark': {
    name: 'dark',
    backgroundColor: '#242526',
    bookCardBGColor: '#3A3B3C',
    cardBGColor: '#3A3B3C',
    navBarBGColor: '#18191A',
    bookTitleColor: '#FEFEFE',
    bookAuthorsColor: '#EEEEEE',
    starColor: '#FEFEFE',
    sectionHeaderColor: '#FEFEFE',
    textColor: '#EEEEEE',
    usernameColor: '#FEFEFE',
    textFieldActiveColor: '#BBBBBB',
    chipColor: '#242526',
    progressPathColor: '#FEFEFE',
    progressTrailColor: '#888888',
    progressTextColor: '#FEFEFE',
    readerBackgroundColor: '#333333',
    readerTextColor: '#FEFEFE',
  }
};

export default Theme;
