export const FETCH_BOOKS = 'FETCH_BOOKS';
export const GET_BOOK_BY_ID = 'GET_BOOK_BY_ID';
export const GET_REVIEWS_BY_BOOK_ID = 'GET_REVIEW_BY_BOOK_ID';
export const GET_CURRENT_USER = 'GET_CURRENT_USER';
export const SET_CURRENT_USER = 'GET_CURRENT_USER';
